package com.apk.manager.hibernate.mapping;

// Generated Sep 23, 2014 3:14:58 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AppDownloadDetails generated by hbm2java
 */
@Entity
@Table(name = "app_download_details", catalog = "apk_manager")
public class AppDownloadDetails implements java.io.Serializable {

	private Integer slNo;
	private int appId;
	private Date date;
	private String downloadIp;

	public AppDownloadDetails() {
	}

	public AppDownloadDetails(int appId, Date date, String downloadIp) {
		this.appId = appId;
		this.date = date;
		this.downloadIp = downloadIp;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "SL_NO", unique = true, nullable = false)
	public Integer getSlNo() {
		return this.slNo;
	}

	public void setSlNo(Integer slNo) {
		this.slNo = slNo;
	}

	@Column(name = "APP_ID", nullable = false)
	public int getAppId() {
		return this.appId;
	}

	public void setAppId(int appId) {
		this.appId = appId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE", nullable = false, length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "DOWNLOAD_IP", nullable = false, length = 45)
	public String getDownloadIp() {
		return this.downloadIp;
	}

	public void setDownloadIp(String downloadIp) {
		this.downloadIp = downloadIp;
	}

}
